version: '3'

services:
  # Frontend Service Configuration
  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: npm run dev

  # Backend Service Configuration
  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - ./backend:/app
    command: node index.js

  # MySQL Service Configuration
  db:
    image: mysql:latest
    container_name: db
    command: --authentication_policy=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: root # กำหนด user ของ root mysql
      MYSQL_DATABASE: tutorial # กำหนด database เริ่มต้นของ mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  # PhpMyAdmin Service Configuration
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db # ระบุ host ที่จะให้ phpmyadmin ไปจัดการ ซึ่งสามารถใส่เป็นชื่อ container name (db) ได้เลย
      PMA_PORT: 3306 # ระบุ port ของ Database
      PMA_USER: root # ระบุ user ของ Database
      PMA_PASSWORD: root # ระบุ password ของ Database
    ports:
      - "8080:80"
    depends_on:
      - db
